#!/usr/bin/env bash

set -euo pipefail

# -----------------------------------------------------------------------------
# CONFIG
# -----------------------------------------------------------------------------

__VERSION="0.1"
__NAME="Faker in Bash"
__FILE=$(basename "$0")
readonly __VERSION __FILE __NAME

o_locale=en

# -----------------------------------------------------------------------------
# PRIVATE interfaces
# -----------------------------------------------------------------------------

function _lorem {
  readarray -t ents < locale/"$o_locale"/lorem.txt
  declare -a words
  for ((i = 0; i < ${1:-1}; i++)); do
    rand=$(perl -e "print int(rand(${#ents[@]}))")
    words+=("${ents["$rand"]}")
  done
  echo "${words[@]}"
}

function _firstname {
  readarray -t ents < locale/"$o_locale"/first-name.txt
  rand=$(perl -e "print int(rand(${#ents[@]}))")
  echo "${ents["$rand"]}"
}

function _lastname {
  readarray -t ents < locale/"$o_locale"/last-name.txt
  rand=$(perl -e "print int(rand(${#ents[@]}))")
  echo "${ents["$rand"]}"
}

function _email {
  readarray -t ents < locale/"$o_locale"/email.txt
  rand=$(perl -e "print int(rand(${#ents[@]}))")
  prefix=$(_firstname)$(_lastname)
  echo "${prefix,,}@${ents["$rand"]}"
}

# -----------------------------------------------------------------------------
# PUBLIC interfaces
# -----------------------------------------------------------------------------

function lorem { # Loremipsum run command: lorem 5 - to get 5 words
  local cnt
  if [[ ${1:-1} =~ ^[0-9]+ ]]; then
    cnt="${1:-1}"
  fi

  _lorem "$cnt"
}

function name { # Firstname + Lastname
  echo "$(_firstname)" "$(_lastname)"
}

function firstname { # Firstname
  _firstname
}

function lastname { # Firstname
  _lastname
}

function email { # E-Mail address
  _email
}

# -----------------------------------------------------------------------------

function _parseOptions {
  while [[ $# -ge 1 ]]; do
    case $1 in

      --locale)
        shift
        o_locale=$1
        shift
        continue
        ;;

    esac

    if [[ $# -gt 0 ]]; then
      shift
    fi
  done
}

function help { # Display this helpful help information
  local functions
  functions=$(grep -E "^function [^_]*?$" "$0" | sed -E "s/ *{ *# */#/g" | column -t -s '#' | sed -E "s/^function /   /g" | sort)
  echo "$__NAME v $__VERSION"
  echo "Usage: $__FILE <task> [args]"
  echo ""
  echo "Tasks:"
  echo "$functions"
  echo ""
  echo "Options:"
  echo "   --locale     en"
  echo ""
}

_parseOptions "$@"

"${@:-help}"
